openapi: 3.0.0
info:
  contact:
    name: Up
  description: Enables finding citations of different papers
  title: Listing API
  version: v1_beta.2.1
servers:
- description: Production
  url: https://api.semanticscholar.org/v1/paper
paths:
  /{identifier}/:
    get:
      description: Gets all details to do with a paper 
      operationId: paper 
      parameters:
      - description: 'Identifier of the paper'
        in: path
        name: identifier
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaperResponse'
          description: OK
components:
  schemas:
    PaperResponse:
      description: The details of the paper
      properties:
        citations:
          $ref: '#/components/schemas/Citation'
    Citation: 
      description: A paper that cites this one
      properties:
        title:
          description: The title of the paper
          type: string
